/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package advent.app


fun main() {
    val file = fileToStringList("app/src/main/kotlin/input/input2_1.txt")
    val fileSize = file.size - 1
    var matches = 0
    for (first in 0..fileSize) {
        if (validPassword(file[first])){
            matches++
        }
    }
    print(matches)
}


fun validPassword(line: String): Boolean {
    val splitLine = line.split(" ")
    val min = splitLine[0].split("-")[0].toInt()
    val max = splitLine[0].split("-")[1].toInt()
    val token = splitLine[1].first()
    val password = splitLine[2]
    val matches = password.filter{ it == token }.count()
    return matches in min..max
}